# Generated by Django 4.1 on 2022-09-07 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PlayerGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="kahoot.playergroup",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("image", models.ImageField(blank=True, upload_to="media/")),
                ("is_active", models.BooleanField(default=True)),
                ("amount_of_quiz", models.IntegerField(default=1)),
                ("count_correct_ans", models.IntegerField(default=0)),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="kahoot.quiz"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("surname", models.CharField(max_length=50)),
                ("number", models.IntegerField()),
                ("login", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=255)),
                ("rating", models.IntegerField(default=0)),
                ("point", models.IntegerField(default=0)),
                ("correct_answers", models.IntegerField(default=0)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="kahoot.playergroup",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AnswerQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer1", models.CharField(max_length=100)),
                ("answer2", models.CharField(max_length=100)),
                ("answer3", models.CharField(max_length=100)),
                ("answer4", models.CharField(max_length=100)),
                ("correct_answer", models.CharField(max_length=100)),
                ("time", models.IntegerField(default=20)),
                ("point", models.IntegerField(default=100)),
                (
                    "quiz",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="kahoot.question",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AnswerPlayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player_answer", models.CharField(max_length=100)),
                ("fact_time", models.IntegerField()),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="kahoot.player"
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="kahoot.quiz"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LeaderBoard",
            fields=[],
            options={"proxy": True, "indexes": [], "constraints": [],},
            bases=("kahoot.player",),
        ),
    ]
