# Generated by Django 4.1 on 2022-09-07 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("kahoot", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryQuiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name="quiz",
            name="title",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="kahoot.categoryquiz"
            ),
        ),
    ]
