# Generated by Django 4.1 on 2022-09-07 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("kahoot", "0002_categoryquiz_alter_quiz_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="title",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="kahoot.categoryquiz"
            ),
        ),
    ]
