# Generated by Django 4.1 on 2022-09-07 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("kahoot", "0004_alter_quiz_title"),
    ]

    operations = [
        migrations.RemoveField(model_name="question", name="quiz",),
        migrations.AddField(
            model_name="quiz",
            name="question",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="kahoot.question",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="quiz", name="title", field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(name="CategoryQuiz",),
    ]
