# Generated by Django 4.1 on 2022-09-07 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kahoot", "0005_remove_question_quiz_quiz_question_alter_quiz_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="title",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
