# Generated by Django 4.1 on 2022-09-07 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kahoot", "0008_quizname_alter_quiz_title"),
    ]

    operations = [
        migrations.RemoveField(model_name="quiz", name="group",),
    ]
