# Generated by Django 4.1 on 2022-09-07 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("kahoot", "0009_remove_quiz_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="question_answer",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="kahoot.answerquestion",
            ),
            preserve_default=False,
        ),
    ]
