# Generated by Django 4.1 on 2022-09-07 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("kahoot", "0010_quiz_question_answer"),
    ]

    operations = [
        migrations.RemoveField(model_name="answerquestion", name="question",),
        migrations.AddField(
            model_name="question",
            name="answer",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="kahoot.answerquestion",
            ),
            preserve_default=False,
        ),
    ]
