# Generated by Django 4.1 on 2022-09-07 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kahoot", "0011_remove_answerquestion_question_question_answer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quizname",
            name="title",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
