# Generated by Django 4.1 on 2022-09-07 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kahoot", "0012_alter_quizname_title"),
    ]

    operations = [
        migrations.RemoveField(model_name="quiz", name="question_answer",),
    ]
