# Generated by Django 4.1 on 2022-09-07 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("kahoot", "0013_remove_quiz_question_answer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="title",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="kahoot.quizname"
            ),
        ),
    ]
