# Generated by Django 4.1 on 2022-09-07 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kahoot", "0014_alter_quiz_title"),
    ]

    operations = [
        migrations.RemoveField(model_name="question", name="amount_of_quiz",),
        migrations.RemoveField(model_name="question", name="count_correct_ans",),
    ]
