# Generated by Django 4.1 on 2022-09-07 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("kahoot", "0015_remove_question_amount_of_quiz_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="answerquestion", name="point",),
        migrations.RemoveField(model_name="answerquestion", name="time",),
        migrations.AddField(
            model_name="quiz",
            name="count_correct_ans",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="quiz",
            name="count_of_question",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="quiz",
            name="group",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="kahoot.playergroup",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="quiz", name="point", field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name="quiz", name="time", field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name="quiz", name="title", field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(name="QuizName",),
    ]
