# Generated by Django 4.1 on 2022-09-07 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("kahoot", "0018_remove_quiz_question_quiz_question"),
    ]

    operations = [
        migrations.RemoveField(model_name="answerplayer", name="quiz",),
        migrations.AddField(
            model_name="answerplayer",
            name="question",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="kahoot.question",
            ),
            preserve_default=False,
        ),
    ]
