# Generated by Django 4.1 on 2022-09-08 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("kahoot", "0022_remove_question_answer_answerquestion_question"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answerquestion",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="kahoot.question"
            ),
        ),
    ]
